### ISSUE TITLE
Trouble registering a new user using the API or Client.

### ISSUE THREAD

**Issue by inacali** [interledger/five-bells-wallet#24]
After using the initial config options in the readme i've got a wallet up and running, am having trouble registering a user, whether using the five bells wallet client or creating my own client using the API. I am running into the following error, whilst registering a user. I've tried to use my own ledger as well as the red.ilpdemo hosted ledger but I get the same error making me think its something else, haven't been able to workout what it is, any help appreciated.

`users.js:113 TypeError: Cannot read property 'body' of undefined
[3]     at Ledger.putAccount (/home/amohame9/five-bells-wallet/api/src/lib/ledger.js:251:20)
[3]     at throw (native)
[3]     at onRejected (/home/amohame9/five-bells-wallet/node_modules/koa.io/node_modules/co/index.js:77:24)
[3]     at process._tickCallback (internal/process/next_tick.js:103:7)
[3] 2016-08-16T07:50:37.122Z error-handler ERROR TypeError: Cannot read property 'id' of undefined
[3]     at Object.postResource (/home/amohame9/five-bells-wallet/api/src/controllers/users.js:138:35)
[3]     at throw (native)
[3]     at onRejected (/home/amohame9/five-bells-wallet/node_modules/koa.io/node_modules/co/index.js:77:24)
[3]     at process._tickCallback (internal/process/next_tick.js:103:7)
[3] 2016-08-16T07:50:37.123Z error-handler ERROR TypeError: Cannot read property 'id' of undefined
[3]     at Object.postResource (/home/amohame9/five-bells-wallet/api/src/controllers/users.js:138:35)
[3]     at throw (native)
[3]     at onRejected (/home/amohame9/five-bells-wallet/node_modules/koa.io/node_modules/co/index.js:77:24)
[3]     at process._tickCallback (internal/process/next_tick.js:103:7)
[3] 2016-08-16T07:50:37.123Z http INFO   xxx POST /users/alice 500 1,223ms -
[3] 
[3]   InternalServerError: TypeError: Cannot read property 'id' of undefined
[3]       at Object.module.exports.throw (/home/amohame9/five-bells-wallet/node_modules/koa.io/node_modules/koa/lib/context.js:90:23)
[3]       at Object.handleError (/home/amohame9/five-bells-wallet/node_modules/five-bells-shared/middlewares/error-handler.js:18:19)
[3]       at throw (native)
[3]       at onRejected (/home/amohame9/five-bells-wallet/node_modules/koa.io/node_modules/co/index.js:77:24)
[3]       at process._tickCallback (internal/process/next_tick.js:103:7)`

**Comment by vhpoet** [comment]
@inacali Could you please show me the environment variables and the exact request you made? That's an internal error and it should never happen, the wallet needs to provide an error message.

**Comment by inacali** [comment]
I've used the following environment variables. 

`API_PRIVATE_HOSTNAME=localhost 
API_HOSTNAME=wallet1.com 
API_PORT=3100 API_PUBLIC_PORT=80 
API_PUBLIC_PATH=/api 
API_DB_URI=postgres://localhost/wallet1 
API_LEDGER_ADMIN_NAME=admin 
API_LEDGER_ADMIN_PASS=admin 
API_RELOAD=true 
CLIENT_HOST=wallet1.com 
CLIENT_PORT=3010 
CLIENT_PUBLIC_PORT=80 
API_SECRET=qO2UX+fdl+tg0a1bYtXoBVQHN4pkn2hFB5Ont6CYj50=  npm run dev`

First without  API_LEDGER_URI env variable, I get an  `InternalServerError: Error: connect ECONNREFUSED 127.0.1.1:3101` when I include my own ledger instance or red.ilpdemo hosted ledger , the wallet runs ok in dev , but I run into my original error when trying to register user. I suspect its a ledger issue as I get the same error when trying to register user without a properly configured ledger. 

I've tried using the register form in the react wallet client. as well as my own client using the backend API

`const request = require('request'),
         auth = 'admin:admin',
         username = 'alice',
         baseUrl = 'http://' + auth + '@wallet1.com/api/users/' + username,
         formData = {"password": username}
request({
  url: baseUrl,
  headers: {'content-type': 'application/json'},
  method: 'POST',
  body: formData,
  json: true
}).pipe(process.stdout)`

**Comment by vhpoet** [comment]
@inacali you can't directly create a user connecting to the red ledger. Your API_LEDGER_ADMIN_NAME and API_LEDGER_ADMIN_PASS wouldn't match the red ledger admin name/pass. You can only create an account on the red/blue wallets by using the wallet api.

It seems to me that your local ledger is not running properly. Could you show me the full logs for running the wallet? Also, did you create both `wallet` and `wallet-ledger` dbs?

**Comment by inacali** [comment]
Oh yes of course, the red.ilp  ledger won't work.  I also suspect its the ledger, I've put the logs outputted here when i run without the API_LEDGER_URI     https://gist.github.com/inacali/89868f8f17f2ffcbd3eae56f63d554d9, the ledger doesn't seem to running. I've created both the databases, made sure they are being used by deleting them and trying to run the wallet which didn't work with the error logs being displayed saying they don't exist.

**Comment by vhpoet** [comment]
@inacali are there more logs? I don't see ledger logs in the file you posted.

**Comment by inacali** [comment]
Here is all their is after the previous log https://gist.github.com/inacali/5b3b096f4d3c41ad3fe77a64fa00d9fb To me it seems, a five bells wallet ledger instance is not automatically running when I leave the API_LEDGER_URI empty.

**Comment by vhpoet** [comment]
@inacali do you have outdated dependencies? looking at the log I don't see the
```
DEPRECATION WARNING: Use LEDGER_PUBLIC_URI instead of LEDGER_PUBLIC_HTTPS, LEDGER_PUBLIC_PORT, LEDGER_PUBLIC_PATH
```
which was added in the ledger recently. Please remove the `node_modules` folder and run `npm install` again.

**Comment by inacali** [comment]
Spot on. didn't notice I was working on an old version I cloned a while back, thanks for that help. Will change title.
