### ISSUE TITLE
This version of Node.js requires NODE_MODULE_VERSION 57. Please try re-compiling or re-installing

### ISSUE THREAD

**Issue by sheena417** [interledger/five-bells-wallet#492]
I attempted to setup ILP with docker.
However, a version difference error on node.js was displayed.
Details are below.

ilp-kit        | was compiled against a different Node.js version using
ilp-kit        | NODE_MODULE_VERSION 51. This version of Node.js requires
ilp-kit        | NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
ilp-kit        | the module (for instance, using `npm rebuild` or `npm install`).
ilp-kit        |     at Object.Module._extensions..node (module.js:664:18)
ilp-kit        |     at Module.load (module.js:554:32)
ilp-kit        |     at tryModuleLoad (module.js:497:12)

Please explain those who know about this event.

**Comment by sharafian** [comment]
This repository is unmaintained and out of date. What is it that you're trying to do? I can point you to the most up-to-date repo for that purpose

**Comment by sheena417** [comment]
@sharafian Thank you comments. I would like to try a remittance test between ripple and proprietary virtual currency using ILP. What should I do to test in a simpler way?
